---
driver:
  name: dokken
  chef_version: latest
  volumes:
  # saves the apt archieves outside of the container
  - /var/cache/apt/archives/:/var/cache/apt/archives/

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: ubuntu-18.04
  driver:
    image: dokken/ubuntu-18.04
    intermediate_instructions:
      - RUN rm /etc/apt/apt.conf.d/docker-clean
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install -y s3cmd 

suites:
  - name: default
    run_list: [ "recipe[logrotate-s3::default]" ]
    verifier:
      inspec_tests: [ "test/smoke/default" ]
